### ISSUE TITLE
some samples can't get any result by NCLscan

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [TreesLab/NCLscan#25]
Hi TreesLab.
In some datasets, I can't get any results by your software. my dataset is PRJNA356761, https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA356761.
Eg. https://www.ncbi.nlm.nih.gov/sra/SRX2405925[accn]
SRX2405925: GSM2420376: Pt35_On_AD485758-6; Homo sapiens; RNA-Seq
1 ILLUMINA (Illumina Genome Analyzer) run: 54.9M spots, 5.6G bases, 3.5Gb downloads
Study: Molecular portraits of tumor mutational and micro-environmental sculpting by immune checkpoint blockade therapy
PRJNA356761 • SRP094781 • 
Sample: Pt35_On_AD485758-6
SAMN06125082 • SRS1844646
 Organism: Homo sapiens
Library: 
Instrument: Illumina Genome Analyzer
Strategy: RNA-Seq
Source: TRANSCRIPTOMIC
Selection: cDNA
Layout: PAIRED
Construction protocol: RNA Later RNASeq
Experiment attributes: 
GEO Accession: GSM2420376 
Runs: 1 run, 54.9M spots, 5.6G bases, 3.5Gb
Could you please help me to check this dataset have any wrong or the need to change any parameter?
Best,
Jian-Guo

**Comment by chiangtw** [comment]
Hi,
There is a parameter "span_range" in the NCLscan.config, 
you may try to decrease the value to 10. 
This would lower the criteria for supporting reads,
and maybe some NCL events would emerge.

tw

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Hi,
> There is a parameter "span_range" in the NCLscan.config,
> you may try to decrease the value to 10.
> This would lower the criteria for supporting reads,
> and maybe some NCL events would emerge.
> 
> tw

Hi tw, thanks for your reply.
I will try it again.
Best,
Jian-Guo

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi, tw @chiangtw I got another error.
But just for this dataset.

````
Reading annotations on chr1.
Reading annotations on chr2.
Reading annotations on chr3.
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 28723, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (79, 93, 115)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (7, 187)
[M::mem_pestat] mean and std.dev: (99.18, 27.22)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 223)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
Reading annotations on chr4.
Reading annotations on chr5.
Reading annotations on chr6.
[M::mem_process_seqs] Processed 2868806 reads in 282.620 CPU sec, 14.774 real sec
Reading annotations on chr7.
Reading annotations on chr8.
Reading annotations on chr9.
Reading annotations on chr10.
Reading annotations on chr11.
[M::process] read 2868338 sequences (200000045 bp)...
Reading annotations on chr12.
Reading annotations on chr13.
Reading annotations on chr14.
Reading annotations on chr15.
Reading annotations on chr16.
Reading annotations on chr17.
Reading annotations on chr18.
Reading annotations on chr19.
Reading annotations on chr20.
Reading annotations on chr21.
Reading annotations on chr22.
Reading annotations on chrX.
Reading annotations on chrY.
Reading annotations on chrM.
Read 60669 genes, 228048 transcripts and 1378888 exons from the gtf file.
# novoindex (3.9) - Universal k-mer index constructor.
# (C) 2008 - 2011 NovoCraft Technologies Sdn Bhd
# novoindex /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.JS.ndx /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.JS.fa 
# Building with 9-mer and step of 1 bp.
# novoindex construction dT = 0.0s
# Index memory size   0.001Gbyte.
# Done.
# Creating 95 indexing threads.
# novoalign (AVX2) (V3.09.00 - Build Jun 12 2018 @ 08:54:15) - A short read aligner with qualities.
# (C) 2008-2016 Novocraft Technologies Sdn Bhd.
# License file: /home/zhou/miniconda2/envs/kn/bin/novoalign.lic
# Licensed to Jian-Guo Zhou MD
#  novoalign -r A 1 -g 99 -x 99 -d /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.JS.ndx -f /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.main.unmapped_1.fastq -o SAM
# Starting at Fri Feb  5 06:55:46 2021
# Interpreting input files as Sanger FASTQ.
# Index Build Version: 3.9
#   Hash length:    9
#     Step size:    1
#     Read Sequences:    13771
#   Unique Alignment:       46 ( 0.3%)
#       Multi Mapped:      164 ( 1.2%)
#   No Mapping Found:    13561 (98.5%)
# Timers
#       Elapsed Time: 0.311 (secs.)
#           CPU Time: 1.38 (secs.)
# Done at Fri Feb  5 06:55:46 2021
# novoalign (AVX2) (V3.09.00 - Build Jun 12 2018 @ 08:54:15) - A short read aligner with qualities.
# (C) 2008-2016 Novocraft Technologies Sdn Bhd.
# License file: /home/zhou/miniconda2/envs/kn/bin/novoalign.lic
# Licensed to Jian-Guo Zhou MD
#  novoalign -r A 1 -g 99 -x 99 -d /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.JS.ndx -f /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.main.unmapped_2.fastq -o SAM
# Starting at Fri Feb  5 06:55:46 2021
# Interpreting input files as Sanger FASTQ.
# Index Build Version: 3.9
#   Hash length:    9
#     Step size:    1
#     Read Sequences:    13771
#   Unique Alignment:        9 ( 0.1%)
#       Multi Mapped:      186 ( 1.4%)
#   No Mapping Found:    13576 (98.6%)
# Timers
#       Elapsed Time: 0.286 (secs.)
#           CPU Time: 1.48 (secs.)
# Done at Fri Feb  5 06:55:46 2021
Start to split the input into 20 part ... 
Traceback (most recent call last):
  File "/home/zhou/soft/NCLscan/bin/mp_blat.py", line 152, in <module>
    mp_blat(args.reference, args.fasta, args.output, args.process, args.tmp_path, args.blat_bin, args.blat_opt)
  File "/home/zhou/soft/NCLscan/bin/mp_blat.py", line 72, in mp_blat
    edge_pos = [all_reads_pos[0]] + splice_positions + [fasta_file_size]
IndexError: list index out of range
cat: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.JS.GRCh37.psl: 没有那个文件或目录
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 43081, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (82, 95, 117)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (12, 187)
[M::mem_pestat] mean and std.dev: (99.95, 25.10)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 222)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
Start to split the input into 20 part ... 
Traceback (most recent call last):
  File "/home/zhou/soft/NCLscan/bin/mp_blat.py", line 152, in <module>
    mp_blat(args.reference, args.fasta, args.output, args.process, args.tmp_path, args.blat_bin, args.blat_opt)
  File "/home/zhou/soft/NCLscan/bin/mp_blat.py", line 72, in mp_blat
    edge_pos = [all_reads_pos[0]] + splice_positions + [fasta_file_size]
IndexError: list index out of range
cat: /home/zhou/raid/ncbi/dbGaP-24835/RNA_phs001464_PRJNA412284/NCLscan/SRR6118673.output/raw.2.info.GRCh37.psl: 没有那个文件或目录
PslChimeraFilter v0.4
````
Could you help me to check this?
Best,
Jian-Guo

**Comment by chiangtw** [comment]
Hi Jian-Guo,

Please provide:
1. the complete log messages
2. and the output of the following command:
    - `ls -ltr /path/to/NCLscan_output_dir`

Best,
tw

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi tw @chiangtw,
Thanks for your reply.
1. This nohup is the complete log messages.
[nohup.out.txt](https://github.com/TreesLab/NCLscan/files/5941838/nohup.out.txt)
2. ls -ltr /path/to/NCLscan_output_dir
````
(base) [zhou@localhost NCLscan]$  ls -ltr ./ SRR6118727.output
./:
总用量 976
drwxrwxr-x 2 zhou zhou   4096 2月   5 06:56 SRR6118673.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:07 SRR6118678.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:17 SRR6118676.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:36 SRR6118680.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:42 SRR6118688.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:53 SRR6118691.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 07:59 SRR6118693.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 08:42 SRR6118696.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:00 SRR6118701.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:05 SRR6118698.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:13 SRR6118705.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:18 SRR6118708.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:23 SRR6118712.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:38 SRR6118718.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 09:48 SRR6118715.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 10:02 SRR6118723.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 10:12 SRR6118720.output
drwxrwxr-x 2 zhou zhou   4096 2月   5 10:29 SRR6118727.output
-rw------- 1 zhou zhou 900010 2月   5 10:51 nohup.out
drwxrwxr-x 2 zhou zhou   4096 2月   5 10:51 SRR6118731.output

SRR6118727.output:
总用量 2873980
-rw-rw-r-- 1 zhou zhou 1337150478 2月   5 10:22 raw.main.bwa.unmapped.sam
-rw-rw-r-- 1 zhou zhou   22217849 2月   5 10:22 raw.main.bwa.unmapped.sam.id
-rw-rw-r-- 1 zhou zhou  232987385 2月   5 10:23 raw.main.bwa.unmapped_1.fastq
-rw-rw-r-- 1 zhou zhou  232410539 2月   5 10:25 raw.main.bwa.unmapped_2.fastq
-rw-rw-r-- 1 zhou zhou  715678643 2月   5 10:25 raw.main.sam
-rw-rw-r-- 1 zhou zhou   46864028 2月   5 10:26 raw.main.unmapped.sam
-rw-rw-r-- 1 zhou zhou    1593500 2月   5 10:26 raw.main.unmapped.sam.id
-rw-rw-r-- 1 zhou zhou   16260600 2月   5 10:26 raw.main.unmapped_1.fastq
-rw-rw-r-- 1 zhou zhou   16255392 2月   5 10:26 raw.main.unmapped_2.fastq
-rw-rw-r-- 1 zhou zhou   12783664 2月   5 10:26 raw.main.unmapped.fa
-rw-rw-r-- 1 zhou zhou   12783664 2月   5 10:26 raw.unmapped.fa
-rw-rw-r-- 1 zhou zhou   83986767 2月   5 10:29 raw.rG.psl
-rw-rw-r-- 1 zhou zhou    4781397 2月   5 10:29 raw.un.psl
-rw-rw-r-- 1 zhou zhou   37025891 2月   5 10:29 raw.rG.non_un.psl
-rw-rw-r-- 1 zhou zhou     616511 2月   5 10:29 raw.chi0.bed
-rw-rw-r-- 1 zhou zhou     749377 2月   5 10:29 raw.unmapped.2.fa
-rw-rw-r-- 1 zhou zhou   31804907 2月   5 10:29 raw.coding.2.psl
-rw-rw-r-- 1 zhou zhou   12767874 2月   5 10:29 raw.lncRNA.2.psl
-rw-rw-r-- 1 zhou zhou      12726 2月   5 10:29 raw.chrM.2.psl
-rw-rw-r-- 1 zhou zhou      11010 2月   5 10:29 raw.colinear.psl
-rw-rw-r-- 1 zhou zhou     613821 2月   5 10:29 raw.chi.bed
-rw-rw-r-- 1 zhou zhou    2689542 2月   5 10:29 raw.preJS.bed
-rw-rw-r-- 1 zhou zhou    2475335 2月   5 10:29 raw.preJS.info
-rw-rw-r-- 1 zhou zhou    1824550 2月   5 10:29 raw.preJS.info2
-rw-rw-r-- 1 zhou zhou     905179 2月   5 10:29 raw.JS.info_1
-rw-rw-r-- 1 zhou zhou    1010098 2月   5 10:29 raw.JS.info_2
-rw-rw-r-- 1 zhou zhou    5556691 2月   5 10:29 raw.JS.info
-rw-rw-r-- 1 zhou zhou     894919 2月   5 10:29 raw.JS.cleaned.info
-rw-rw-r-- 1 zhou zhou    4862584 2月   5 10:29 raw.preJS.seq
-rw-rw-r-- 1 zhou zhou    4146114 2月   5 10:29 raw.preJS.seq2
-rw-rw-r-- 1 zhou zhou    1852227 2月   5 10:29 raw.JS.seq_1
-rw-rw-r-- 1 zhou zhou    2293885 2月   5 10:29 raw.JS.seq_2
-rw-rw-r-- 1 zhou zhou   12991176 2月   5 10:29 raw.JS.seq12
-rw-rw-r-- 1 zhou zhou    2115472 2月   5 10:29 raw.JS.seq
-rw-rw-r-- 1 zhou zhou    2121970 2月   5 10:29 raw.JS.fa
-rw-r--r-- 1 zhou zhou    9932301 2月   5 10:29 raw.JS.ndx
-rw-rw-r-- 1 zhou zhou   16705227 2月   5 10:29 raw.main_1.JS.sam
-rw-rw-r-- 1 zhou zhou   16686601 2月   5 10:29 raw.main_2.JS.sam
-rw-rw-r-- 1 zhou zhou   33391828 2月   5 10:29 all.raw.JS.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.JS.Parsered.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 tmp.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS.clear.fa
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS.GRCh37.2.psl
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.linearJS
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.tmp.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.tmp2.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.2.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.2.info.fa
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.2.chi.bed
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 temp.list
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.chi2.bed
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.chi3.bed
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.PreJS2.bed
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.PreJS2.info
-rw-rw-r-- 1 zhou zhou          2 2月   5 10:29 raw.PreJS2.info2
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.info_1
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.info_2
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.cleaned.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.preIdx
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS1.preIdx
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS1.Idx
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.Idx
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.PreJS2.seq
-rw-rw-r-- 1 zhou zhou          2 2月   5 10:29 raw.PreJS2.seq2
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.seq_1
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.seq_2
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.seq
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.prefa
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.fa
-rw-r--r-- 1 zhou zhou    1049069 2月   5 10:29 raw.JS2.ndx
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.main.JS2.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.1.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.1.result
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.JS2.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.ncl.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.result
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.JS2.result.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.result.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.2b.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.3.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.4.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.preResult
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.main_1.um3.fastq
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.main_2.um3.fastq
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.main.um3.fa
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.um3.fa
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.um3.colinear.psl
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.main.JS2b.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.1b.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.1b.result
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.JS2b.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.result.sam
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 all.raw.b.result
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.3b.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.4b.info
-rw-rw-r-- 1 zhou zhou          0 2月   5 10:29 raw.result.tmp
(base) [zhou@localhost NCLscan]$ 
````
Best,
Jian-Guo

**Comment by chiangtw** [comment]
Hi Jian-Guo,

Sorry for the late reply.

From your log messages, it shows that the NCL candidates were all filter out in early steps.

thanks,
tw

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Hi Jian-Guo,
> 
> Sorry for the late reply.
> 
> From your log messages, it shows that the NCL candidates were all filter out in early steps.
> 
> thanks,
> tw

Hi @chiangtw tw, how to solve this question?
Best,
Jian-Guo

**Comment by chiangtw** [comment]
Hi Jian-Guo,

Since the properties of the datasets(*polyA+*, *single-end*, and *short read length*) are unfavorable for NCL events detecting, 
it should be regarded as **no NCL events were detected** from these datasets by NCLscan.

tw

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Hi Jian-Guo,
> 
> Since the properties of the datasets(_polyA+_, _single-end_, and _short read length_) are unfavorable for NCL events detecting,
> it should be regarded as **no NCL events were detected** from these datasets by NCLscan.
> 
> tw

Hi tw, so based on NCLscan I can't detect any event, however, CIRCexplorer2 worked.
So, based on your personal view, Can I use these circRNA results from CIRCexplorer2 to do the next step work?
Best,
Jian-Guo

**Comment by TreesLab** [comment]
Hi, Jian-Guo

 

Since circRNAs are generally non-polyadenylated, we do not identify circRNA candidates using ployA+ reads. 

 

To increase the accuracy, I suggest that you can apply NCLcomparator to the results from CIRCexplorer2. NCLcomparator can further eliminate potential ambiguous alignments when detecting NCL events (BMC Bioinformatics, 20:3, 2019). 

 

TJ Chuang

==========================

Trees-Juen Chuang, Ph.D.

Research Fellow/Professor

Genomics Research Center

Academia Sinica

Taipei 11529

Taiwan

**Comment by chiangtw** [comment]
> Hi Jian-Guo,
> 
> Since the properties of the datasets(_polyA+_, _single-end_, and _short read length_) are unfavorable for NCL events detecting,
> it should be regarded as **no NCL events were detected** from these datasets by NCLscan.
> 
> tw

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi Prof. TJ Chuang,
Thanks for your warm reply.
I will check your NCLcomparator paper.
Best,
Jian-Guo

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> Hi,
> There is a parameter "span_range" in the NCLscan.config,
> you may try to decrease the value to 10.
> This would lower the criteria for supporting reads,
> and maybe some NCL events would emerge.
> 
> tw

Hi Dr. Chuang,
I checked NCLscan is worked for pair-end RNA-seq, could you please share some tools for single end mRNA sequencing data?
Best,
JG
