### ISSUE TITLE
can not generate the CircRNA with NCLscan version 

### ISSUE THREAD

**Issue by JianGuoZhou3** [TreesLab/NCLscan#29]
````
(base) zhou2@zhou2-Super-Server:~$ conda activate kn

(kn) zhou2@zhou2-Super-Server:~$ 
(kn) zhou2@zhou2-Super-Server:~$ /home/zhou2/soft/NCLscan-1.7.0/NCLscan.py
usage: NCLscan.py [-h] [-c CONFIG] [--fq1 FQ1] [--fq2 FQ2] [-pj PROJECT_NAME]
                  [-o OUTPUT_DIR]

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        The config file of NCLscan.
  --fq1 FQ1             The 1st end of the paired-end reads.
  --fq2 FQ2             The 2nd end of the paired-end reads.
  -pj PROJECT_NAME, --project_name PROJECT_NAME
  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
(kn) zhou2@zhou2-Super-Server:~$ 
````

**Comment by JianGuoZhou3** [comment]
````
    nohup /home/zhou2/soft/NCLscan-1.7.0/NCLscan.py -c /home/zhou2/soft/NCLscan-1.7.0/NCLscan.config -pj raw -o ${dir}/NCLscan/${i}.output --fq1 ${dir}/raw/${i}_1.fastq.gz --fq2 ${dir}/raw/${i}_2.fastq.gz
````
There are some errors.
````
# novoindex (4.3) - Universal k-mer index constructor.
# (C) 2008 - 2011 NovoCraft Technologies Sdn Bhd
# novoindex /home/data/EGA/IMmotion151/NCLscan/WO29637_ngs_rna_targrna_EA_001b0af504.output/raw.JS2.ndx /home/data/EGA/IMmotion151/NCLscan/WO29637_ngs_rna_targrna_EA_001b0af504.output/raw.JS2.fa 
# Creating 127 indexing threads.
# Building with 9-mer and step of 1 bp.
#             0 kmers were indexed.
#             0 kmers not indexed due to excess N's.
# novoindex construction dT = 0.0s
# Index memory size   0.001Gbyte.
# Done.
Error: /home/data/EGA/IMmotion151/NCLscan/WO29637_ngs_rna_targrna_EA_001b0af504.output/raw.JS2.ndx does not appear to be a valid novoindex. Code 9
Start to split the input into 20 part ... 
Traceback (most recent call last):
  File "/home/zhou2/soft/NCLscan-1.7.0/bin/mp_blat.py", line 152, in <module>
    mp_blat(args.reference, args.fasta, args.output, args.process, args.tmp_path, args.blat_bin, args.blat_opt)
  File "/home/zhou2/soft/NCLscan-1.7.0/bin/mp_blat.py", line 72, in mp_blat
    edge_pos = [all_reads_pos[0]] + splice_positions + [fasta_file_size]
IndexError: list index out of range
````

**Comment by JianGuoZhou3** [comment]
[nohup.out.txt](https://github.com/TreesLab/NCLscan/files/9374623/nohup.out.txt)

**Comment by JianGuoZhou3** [comment]
@TreesLab @chiangtw @chenchiaying
